apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: msp-apps
  namespace: argocd
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      github:
        organization: Mobility-Scooter-Project
        appSecretName: argocd-gh
      filters:
        - branchMatch: main #^sarina-development$
          pathsExist:
          - deploy
  goTemplate: true
  template:
    metadata:
        name: '{{ .repository | normalize }}'
        namespace: argocd
    spec:
      source:
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: deploy
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
